// <auto-generated />
using System;
using AquaLink.Prices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaLink.Prices.Infrastructure.Migrations
{
    [DbContext(typeof(AquaLinkPricesDbContext))]
    partial class AquaLinkPricesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaLink.Prices.Domain.Entities.FarmerAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AlertDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageSent")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId", "AlertDate")
                        .IsUnique();

                    b.ToTable("FarmerAlerts");
                });

            modelBuilder.Entity("AquaLink.Prices.Domain.Entities.PriceIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PriceNairaPerKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmittedByAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Market", "Commodity", "PriceDate");

                    b.ToTable("PriceIndexes");
                });
#pragma warning restore 612, 618
        }
    }
}
