// <auto-generated />
using System;
using AquaLink.Farmer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaLink.Farmer.Infrastructure.Migrations
{
    [DbContext(typeof(AquaLinkFarmerDbContext))]
    partial class AquaLinkFarmerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaLink.Farmer.Domain.Entities.FarmCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpectedHarvestAt")
                        .HasColumnType("date");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PondSizeSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StockedAt")
                        .HasColumnType("date");

                    b.Property<int>("StockedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FarmCycles");
                });
#pragma warning restore 612, 618
        }
    }
}
